### PR TITLE
upgrade remaining nibs

### PR DESCRIPTION
**Pull request by ptgoetz**
Small change. I just wanted to register my interest.

Over the weekend I found myself doing the same thing... just get the thing running and fix some bugs so it can be useful to others. Trying to track down the original author, I found your effort. And it looks like you're a lot further along, and a lot more adept at OSX dev then I am (I'm about 8 years rusty).

Anyway, happy to help where I can.

### CODE REVIEW

**Comment by ptgoetz** [comment]
Don't merge this. It breaks most toolbar/popup menu functionality. I'm investigating.

**Comment by ptgoetz** [comment]
Ignore previous (deleted) comment about this change breaking things. I had failed to rebuild during testing.

**Comment by srbaker** [comment]
Great, thanks!

I have had a few crashing issues with the nibs, but I wasn't sure what was causing them. I will try out your changes.

I have plans for CocoaFIBS (including a rename, although I don't know what to yet) and fixing crashing bugs is certainly high on my priority list.

Thanks!

**Comment by srbaker** [comment]
Merged. Thanks!

**Pull request merged**
